### Podatkovno rudarjenje, 3. domača naloga, 15. 5. 2018

# Napovedovanje vrednosti

Milosh Kostadinovski

Spoznali bomo praktično uporabo enostavnih metod nadzorovanega modeliranja oz.
napovedovanja.  Skupna lastnost vseh omenjenih metod je, da s pomočjo
naključnih spremenljivk (atributov) modelirajo vrednosti posebne spremenljivke,
ki ji pravimo *razred* (v kontekstu uvrščanja v razrede, klasifikacije)
ali *odziv* (v kontekstu regresije). Osnovne razlike med kontekstoma smo
spoznali na predavanjih in vajah.

Praktična cilja, ki ju bomo zasledovali sta:
* modeliranje ocen posameznega uporabnika (odziva) s pomočjo vseh ostalih uporabnikov,
* primerjava metod nadzorovanega modeliranja.

## Podatki

Opis podatkovne zbirke MovieLens 1996-2016 ostaja enak prvi nalogi.

## Predpriprava podatkov

Za potrebe te naloge bomo podatke pripravili na naslednji način:
1. Izberi $m$ filmov z vsaj 100 ogledi.
2. Izberi $n$ uporabnikov, ki si je ogledalo vsaj 100 filmov.
3. Pripravi matriko $X$ velikosti $m \times n$, kjer vrstice predstavljajo filme, stolpci pa uporabnike. Neznane vrednosti zamenjaj z $0$.

Za vsakega od izbranih $n$ uporabnikov bo zgrajen regresijski model, 
katerega cilj bo napoved ocen za filme.

<table>
    <tr style="background-color: white;">
        <td style="border-right: 1px solid #000;"></td>
        <td></td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">$y^{(0)}$</td>
        <td colspan=3 style="text-align:center;">$X^{(0)}$</td>
    </tr>
    <tr style="border-bottom: 1px solid #000;">
        <td style="border-right: 1px solid #000;"></td>
        <td>Film/uporabnik</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">$u_0$</td>
        <td>$u_1$</td>
        <td>$u_2$</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_1}$</td>
        <td>Twelve Monkeys (a.k.a. 12 Monkeys) (1995)</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">0</td>
        <td>0</td>
        <td>2.5</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_2}$</td>
        <td>Dances with  Wolves (1990) </td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">4</td>
        <td>0</td>
        <td>0</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_3}$</td>
        <td>Apollo 13 (1995)</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">0</td>
        <td>2</td>
        <td>0</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_4}$</td>
        <td>Sixth Sense, The (1999)</td><td style="border-right: 1px solid #000; border-left: 1px solid #000;">3</td>
        <td>0</td>
        <td>4</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">$\cdots$</td>
        <td>$\cdots$</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">$\cdots$</td>
        <td>$\cdots$</td>
        <td>$\cdots$</td>
        <td>$\cdots$</td>
    </tr>
</table>

<table>
    <tr style="background-color: white;">
        <td style="border-right: 1px solid #000;"></td>
        <td></td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">$y^{(1)}$</td>
        <td colspan=3 style="text-align:center;">$X^{(1)}$</td>
    </tr>
    <tr style="border-bottom: 1px solid #000;">
        <td style="border-right: 1px solid #000;"></td>
        <td>Film/uporabnik</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">$u_1$</td>
        <td>$u_0$</td>
        <td>$u_2$</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_1}$</td>
        <td>Twelve Monkeys (a.k.a. 12 Monkeys) (1995)</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">0</td>
        <td>0</td>
        <td>2.5</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_2}$</td>
        <td>Dances with  Wolves (1990) </td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">0</td>
        <td>4</td>
        <td>0</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_3}$</td>
        <td>Apollo 13 (1995)</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">2</td>
        <td>0</td>
        <td>0</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">${f_4}$</td>
        <td>Sixth Sense, The (1999)</td><td style="border-right: 1px solid #000; border-left: 1px solid #000;">0</td>
        <td>3</td>
        <td>4</td>
        <td>$\cdots$</td>
    </tr>
    <tr>
        <td style="border-right: 1px solid #000;">$\cdots$</td>
        <td>$\cdots$</td>
        <td style="border-right: 1px solid #000; border-left: 1px solid #000;">$\cdots$</td>
        <td>$\cdots$</td>
        <td>$\cdots$</td>
        <td>$\cdots$</td>
    </tr>
</table>

Razdelitev podatkov za model uporabnika $u_0$ (zgoraj) in uporabnika $u_1$ (spodaj).

## Vprašanja

<ol>
<li>(100%) **Regresija**. Za vsakega od uporabnikov postavite regresijski model. Uporabite eno ali več metod za učenje regresijskih modelov (linearna regresija, Ridge, Lasso, itd.). <br>
    Za vsakega od $n$ uporabnikov izberite ustrezni stolpec v matriki podatkov. Za uporabnika $i$ imamo torej
    <ul>
    <li> Vektor odziva $y^{(i)}$,</li>
    <li> Matriko podatkov $X^{(i)}$, ki vsebuje vse stolpce *razen* $i$.</li>
    </ul>
    
Za lažjo predstavo si oglej zgornji tabeli. Nekajkrat (npr. trikrat) ponovite postopek preverjanja s pomočjo učne in testne množice:

    <ol type="a">
    <li> Množico filmov, ki si jih je uporabnik ogledal, *naključno* razdelite v razmerju 75% (učna množica) in 25% (testna množica).</li>
    <li> Naučite regresijski model na učni množici<br> (izberite ustrezne vrstice v $X$ in $y$).</li>
    <li> Ovrednotite model na testni množici <br> (ponovno izberite ustrezne vrstice v $X$ in $y$).</li>
    </ol>
Oceno vrednotenja nato delite s številom poizkusov, da dobite končno oceno.<br>

Poročajte o uspešnosti vašega modela. Pri tem se osredotočite na naslednja vprašanja:
<ul>
    <li> Utemeljite ustrezno mero vrednotenja. Ali model dobro napoveduje ocene?
    <li> Z izbrano mero ocenite modele za vseh $n$ uporabnikov.
</ul>

</li>


<li>
(Bonus 15%) Ustvarite novega uporabnika, ki predstavlja vaše ocene
filmov. Ocenite nekaj filmov po lastnem okusu in preverite, kako modeli ocenijo neizbrane filme.
Ali se vam zdijo napovedi primerne? 
</li>
</ol>

## Zapiski

Implementacijo, opis in vrednotenje metod za nadzorovanjo učenje vsebujejo knjižnice `sklearn` ali `Orange`.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

from sklearn.metrics import mean_squared_error

In [3]:
ratings = pd.read_csv('ml-latest-small/ratings.csv')
movies  = pd.read_csv('ml-latest-small/movies.csv')

##### m = vsi filmi s 100 ali več ogledov
##### n = vsi uporabniki, ki so si ogledali 100 ali več filmov

In [4]:
# grupiramo po movieId
rating_groups = ratings.groupby('movieId', as_index = False).agg({'timestamp': np.size})
# id-ji filmov, ki imajo 100 ali več ogledov
movie_ids = (rating_groups[rating_groups["timestamp"] >= 100])["movieId"]
# grupiramo po userId
rating_groups = ratings.groupby('userId', as_index = False).agg({'timestamp': np.size})
# uporabniki, ki so si ogledali 100 ali več filmov
user_ids = (rating_groups[rating_groups["timestamp"] >= 100])["userId"]
# grupiramo po userId, da bi lahko dobili vse filme, ki so si jih vsi uporabniki ogledali
rating_groups = ratings.groupby('userId', as_index = False)

In [5]:
# ustvarimo nov dataframe, ki kot stolpce uporabi movieId in vsebino seznama user_id (id-ji uporabnikov)
new_df = pd.DataFrame(columns=['movieId'] + list(user_ids))

In [6]:
# v data frame dodamo vse id-je filmov
for id in movie_ids:
    new_df = new_df.append({"movieId": id}, ignore_index=True)

/home/permint/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  This is separate from the ipykernel package so we can avoid doing imports until

In [7]:
# ustavimo vrednosti v dataframe
for a in rating_groups.groups:
    temp = rating_groups.get_group(a)["userId"]
    if len(temp) < 100:
        continue
    user_id = rating_groups.get_group(a)["userId"]
    user_id = user_id.iloc[0]
    movie_id = rating_groups.get_group(a)["movieId"]
    rating = rating_groups.get_group(a)["rating"]
    for id, r in zip(movie_id, rating):
        if (id == new_df["movieId"]).any():
            (new_df[new_df["movieId"] == id])
            new_df.at[id, user_id] = r
# zamenjamo neznane vrednosti (Nan) z 0
new_df = new_df.fillna(0);

In [8]:
# spremenimo podatkovni tip movieId stolpca v int
new_df["movieId"] = new_df['movieId'].astype(int)

In [9]:
matrix = new_df.as_matrix()

linear_regression = LinearRegression()
ridge = Ridge()
lasso = Lasso()
knn_5 =  KNeighborsRegressor(15)
knn_10 =  KNeighborsRegressor(15)
knn_15 =  KNeighborsRegressor(15)
svm = SVR(kernel='rbf', C=1e3, gamma=0.1)

models = [linear_regression, ridge, lasso, knn_5, knn_10, svm, knn_15]
names = ["Linearna regresija", "Ridge", "Lasso", "KNN 5", "KNN 10", "SVM", "KNN 15"]
for m in range(len(names)): 
    total_mse = 0.0
    for column in range(1, matrix.shape[1]):
        current_mse = 0.0
        for i in range(4):
            # nakljucno premesano matriko
            np.random.shuffle(matrix)
            # locimo ucne atribute in ciljni atribut
            y = matrix[:, column]
            x1 = matrix[:, 0:column]
            x2 = matrix[:, column + 1:]
            x = np.concatenate((x1, x2), 1)

            # Razdelimo na ucno in testno mnozico
            y_train = y[:int(len(y) * 0.75)]
            y_test  = y[int(len(y) * 0.75):]

            x_train = x[:int(len(x) * 0.75), :]
            x_test  = x[int(len(x) * 0.75):, :]

            # Ucenje modela
            model = models[m]
            model.fit(x_train, y_train)
            # Napoved vrednosti za podatke
            hx = model.predict(x_test)
            # Evalvacija modela
            mse      = mean_squared_error(hx, y_test)

            current_mse += mse
    
        total_mse += (current_mse / 4)

    total_mse /= matrix.shape[1]
    print(names[m], total_mse)

Linearna regresija 1.9630046568911796
Ridge 1.9571784980724745
Lasso 1.8183365791461292
KNN 5 1.504697525018706
KNN 10 1.521607451833145
SVM 2.380229129820859
KNN 15 1.5047207900766928

#### KNN15 naredi najmanjšo napako. Če korenimo napako (RMSE) dobimo 1.2, kar pomeni, da model v povprečju zgreši za eno oceno. Napovedi niso zelo slabe in tudi niso zelo dobre.

## 2. Naloga

In [14]:
ratings

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [12]:
my_ratings = np.array([1])
hx  = model.predict(x_test)
mse = mean_squared_error(hx, my_ratings)

ValueError: Found input variables with inconsistent numbers of samples: [72, 1]